### ISSUE TITLE
Crash bug with @function/alias

### ISSUE THREAD

**Issue by grapenut** [pennmush/pennmush#1203]
PennMUSH will crash after running the command @function/alias without any arguments. The call to strupper_r() happens without checking if alias is NULL, which causes a crash when strupper_r() tries to access that NULL pointer.

Should probably add a check for !s in strutil.c : strupper_r() around line 390. Something like
```
if (!s) {
  if (!d)
    return "";
  d[0] = '\0';
  return d;
}
```

Here is the core stack trace.

```
(gdb) where
#0  strupper_r (s=0x0, d=d@entry=0x7ffd3354aa30 "\377\377\377\377", len=len@entry=8192) at strutil.c:390
#1  0x0000000000472244 in alias_function (player=5, function=function@entry=0x17ff1e0 "", alias=<optimized out>) at function.c:1195
#2  0x000000000042e288 in cmd_function (cmd=<optimized out>, executor=5, enactor=<optimized out>, caller=<optimized out>, sw=<optimized out>, raw=<optimized out>,
    switches=0x0, args_raw=0x7ffd3355729f "", arg_left=0x17ff1e0 "", args_left=0x7ffd3354ec60, arg_right=0x5bd3ce "", args_right=0x7ffd3354ee60, queue_entry=0x17b0da0)
    at cmds.c:601
#3  0x000000000043408c in run_command (cmd=cmd@entry=0x1550770, executor=executor@entry=5, enactor=5, cmd_evaled=cmd_evaled@entry=0x8a0560 <commandraw> "@FUNCTION/alias",
    sw=sw@entry=0x17b74b0 " ", switch_err=switch_err@entry=0x7ffd3354f060 "", cmd_raw=cmd_raw@entry=0x7ffd33557290 "@function/alias", swp=swp@entry=0x0,
    ap=ap@entry=0x7ffd3355729f "", ls=0x17ff1e0 "", lsa=lsa@entry=0x7ffd3354ec60, rs=rs@entry=0x5bd3ce "", rsa=rsa@entry=0x7ffd3354ee60,
    queue_entry=queue_entry@entry=0x17b0da0) at command.c:1613
#4  0x0000000000434ad3 in command_parse (player=player@entry=5, string=string@entry=0x7ffd33557290 "@function/alias", queue_entry=queue_entry@entry=0x17b0da0)
    at command.c:1474
#5  0x0000000000499297 in process_command (executor=executor@entry=5, command=command@entry=0x7ffd33557290 "@function/alias", queue_entry=queue_entry@entry=0x17b0da0)
    at game.c:1222
#6  0x000000000043d2f0 in do_entry (entry=entry@entry=0x17b0da0, include_recurses=include_recurses@entry=0) at cque.c:1162
#7  0x000000000043daaa in run_user_input (player=5, port=21, input=input@entry=0x180adf0 "@function/alias") at cque.c:1091
#8  0x0000000000420e8e in do_command (d=d@entry=0x15a0560, command=<optimized out>) at bsd.c:3572
#9  0x000000000040c37b in process_commands () at bsd.c:3388
#10 shovechars (sslport=<optimized out>, port=<optimized out>) at bsd.c:1190
#11 main (argc=<optimized out>, argv=<optimized out>) at bsd.c:704
```

**Comment by grapenut** [comment]
FYI it apparently doesn't require any privileges to trigger this bug, or to add a proper function alias. That seems like a bug. Should require Wizard to use @function/alias.
